
networks :
  network :
    driver : bridge

services :
  bot :
    container_name : bot
    build : ./bot
    ports :
      - 5001:5001
    networks :
      - network

  vulnerable_app :
    container_name : vulnerable_app
    build : ./vulnerable_app
    ports :
      - 5000:5000
    networks :
      - network